#+TITLE: Acerca de...

* ... el autor
Mi nombre es Juan Castro, tengo un gran interés por la tecnología, la lectura y los videojuegos.

En lo relacionado a la tecnología, puedo decir que desde hace aproximadamente cuatro años comencé a usar GNU/Linux en mis computadoras y desde entonces no he vuelto atrás; comencé con Xubuntu 16.04, pero actualmente uso Arch Linux, btw. Con un interés similar, hace aproximadamente dos años comencé a usar /Tiling Window Managers/ en lugar de los clásicos entornos de escritorio. Después de inicarme en i3 y vivir un muy buen tiempo en bspwm, actualmente uso mi propia versión de dwm.

Apesar de mi gusto por la tecnología, mis estudios son de educación, específicamente soy Licenciado en educación secundaria con especialidad en matemáticas, o dicho de forma común, profesor de matemáticas. Desde muy pequeño quise ser profesor, y puedo decir que es una profesión que disfruto mucho y me ha dejado grandes experiencias. 

¿Mis redes sociales? Nunca he usado instagram ni twitter de foma activa y dejé de usar facebook hace un año ¡y no me arrepiento! Hoy paso la mayor parte de mi tiempo /online/ en otras fuentes de entretenimiento, como YouTube (ya que no tiene alternativa, aunque espero que LBRY tome algo de fuerza en el futuro), reddit, y de vez en cuando, mastodon y 4chan. Y no, no estoy desconectado del mundo y me sigo enterando de las cosas importantes que suceden en mi ciudad, en mi país y en el mundo.

Si deseas ponerte en contacto conmigo puedes hacerlo en [[https://mstdn.mx/@juacq97][Mastodon]], [[https://github.com/juacq97][GitHub]] o directamente por e-mail a juacq97@tutanota.com

* ...este blog

Este blog surge como resultado de mi interes en el /blogging/ como una forma de expresar mis opiniones, así como escribir sobre temas que me interesan y que, en algunos casos, tiene poca cobertura en español, mi idioma natal. He de decir que, a pesar que puede ser un tema recurrente, este no pretende ser un blog sobre tecnología, mas un blog personal, donde simplemente abarco los temas que a mi me interesan y me llaman la atención.

Técnicamente hablando, este blog está hospedado en GitHub gracias a [[https://pages.github.com/][GitHub Pages]]. El sitio está construido con el generador de sitios dinámicos [[gohugo.io][Hugo]], un programa que encuentro relativamente fácil de usar (una vez que logras captar lo básico y armar un sitio). En cuanto al tema, uso el tema [[https://github.com/vividvilla/ezhil][Ezhil]].

Este no es mi primer blog, antes mantuve un pequeño blog en una instancia de [[https://writefreely.org/][Write Freely]] llamada [[qua.name]]. Decidí mudarme debido a mi interés de poder escribir algunos posts tanto en español como en inglés, ya que paso la mayor parte de mi tiempo en foros y subrredits donde el idioma que se utiliza es el inglés, y gracias a Hugo puedo agregar fácilmente un botón para cambiar el idioma de los posts (localizado en el pie de la página).
